# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - run: cp .env.example .env
      - run: yarn install
      - run: yarn prisma generate
      - run: yarn tsc
      - run: yarn build
