name: Test and Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2

      - run: cp .env.example .env
      - run: yarn install
      - run: yarn prisma generate
      - run: yarn tsc
      - run: yarn test
      - run: yarn build
