name: Test and Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: cp .env.example .env
      - run: npm install
      - run: npm run prisma generate
      - run: npm run tsc
      - run: npm run test
      - run: npm run build
